### ISSUE TITLE
Issue with syntax

### ISSUE THREAD

**Issue by r3dlobst3r** [aaearon/ss-plex-proxy#3]
Hey, I am having issues with my rpi zero running the proxy:

`pi@raspberrypi:~/ss-plex-proxy $ python3 ss-plex-proxy.py
Traceback (most recent call last):
  File "ss-plex-proxy.py", line 6, in <module>
    from pysmoothstreams.auth import AuthSign
  File "/home/pi/.local/lib/python3.5/site-packages/pysmoothstreams/auth.py", line 24
    logging.debug(f'Created {self.__class__.__name__} with username {self.username} and service {self.service}')
                                                                                                              ^
SyntaxError: invalid syntax`

Thanks!

**Comment by aaearon** [comment]
Please try with a version of python newer than 3.5. F strings were introduced in 3.6
